### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by F11GAR0** [imbicile/imbicile.nfs#1]
В следующих файлах были обнаружены опечатки, увидеть которые я смог только через пол часа ковыряний.
foldes -> folde**r**s

templates/example.j2
```j2
{% for folders in nfs_folders %}                                                    <------ исправить с nfs_foldes на nfs_folders
{{ folders.path }} {{ folders.address }}{{ folders.permissions }}
{% endfor %}
```
tasks/main.yml

```yml
- name: create nfs directory
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  loop: "{{ nfs_folders }}"                                                  <------ исправить с nfs_foldes на nfs_folders
  when: nfs_folders_create                                                   <------ исправить с nfs_foldes_create на nfs_folders_create
```
